config/routes.rb
Giftrapped::Application.routes.draw do
  resource :query, :path => '', :only => [:create,:show]
  resources :words, :path => 'words', :except => [:index,:show]
  

end

app/models/query.rb
require 'word_matcher'

class Query
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend  ActiveModel::Naming

  attr_accessor :word, :id, :text, :match_details, :match_string
  attr_accessor :word_type, :dictionary
  validate :found_a_word

  def found_a_word
    if @word
      true
    else
      errors[:base] << "The word you entered doesn't match any we know of."
      false
    end
  end

  def initialize params = {}
    @match_string = params[:match_string] || ""
    @word_type = params[:word_type] || ""
    @dictionary = params[:dictionary] || "0"
    @auto_complete = params[:autocomplete] || "words"
    @term = params[:term] || false
    @number_of_results = 13
    if params[:id].present?
      @id = params[:id].to_i
      @word = Word.find(@id)
      @text = @word.name
    else
      @text = params[:text].present? ? parse_text(params[:text]) : ""
      @word = Spelling.where(:label => @text).try(&:first).try(&:words).try(&:first) || nil
      @id = @word.id if @word
    end
    if @word
      if @match_string == ""
        @match_details = parse_match_string perfect_rhyme_match_string
      else
        @match_details = parse_match_string @match_string
      end
    end
  end

  def parse_match_string string
    string.split(",").map { |e|
      if e.include?(":")
        split_e = e.split(":")
        if split_e.length == 2
          [split_e[0].to_i,split_e[1]!="false"]
        else
          split_e.map { |ee|
            split_ee = ee.split(";")
            [split_ee[0],split_ee[1]!="false"]
          }
        end
      else
        false
      end
    }
  end

  def parse_text text
    # text.downcase.split(" ").last.split("-").last
    text.downcase.split(" ").last
  end

  def persisted?
    false
  end

  def perfect_rhyme_match_string
    num = @word.last_stressed_syllable
    num = ((@word.syllables.length - num) > 3) ? (@word.syllables.length - 3) : num
    word_syllables = @word.syllables.reverse[num..-1]
    word_syllables_str = word_syllables.each_with_index.map { |s,i|
      if i == 0
        "#{s.onset.label};false:#{s.nucleus.label}#{s.stress};true:#{s.coda.label};true" 
      else
        "#{s.onset.label};true:#{s.nucleus.label}#{s.stress};true:#{s.coda.label};true" 
      end
    }.join(",")
    return "false,0:true," + (["false,"]*num).join("") + word_syllables_str + ",false,false"
  end

  def vowels_only_match_string
    num = @word.last_stressed_syllable
    num = ((@word.syllables.length - num) > 3) ? (@word.syllables.length - 3) : num
    word_syllables = @word.syllables.reverse[num..-1]
    word_syllables_str = word_syllables.each_with_index.map { |s,i|
      if i == 0
        "#{s.onset.label};false:#{s.nucleus.label}#{s.stress};true:*;true" 
      else
        "*;true:#{s.nucleus.label}#{s.stress};true:*;true" 
      end
    }.join(",")
    return "false,0:true," + (["false,"]*num).join("") + word_syllables_str + ",false,false"
  end

  def portmanteau1_match_string
    num = @word.syllables.length - 1
    word_syllables = @word.syllables.reverse[-1..-1]
    word_syllables_str = word_syllables.map { |s|
      "#{s.onset.label};true:#{s.nucleus.label}#{s.stress};true:#{s.coda.label};true" 
    }.join(",")
    return "false,false," + (["false,"]*num).join("") + word_syllables_str + ",1:true,false"
  end

  def portmanteau2_match_string
    num = @word.syllables.length - 1
    word_syllables = @word.syllables.reverse[0..0]
    word_syllables_str = word_syllables.map { |s|
      "#{s.onset.label};true:#{s.nucleus.label}#{s.stress};true:#{s.coda.label};true" 
    }.join(",")
    return "false,1:true," + word_syllables_str + ([",false"]*num).join("") + ",false,false"
  end

  def match_total_syllables
    num = @match_details[0] ? 1 : (@match_details[-1] ? 1 : 0)
    num += (@match_details[1] ? @match_details[1][0] : (@match_details[-2] ? @match_details[-2][0] : 0))
    return num + match_word_syllables
  end

  def match_word_syllables
    return @match_details[2..-3].inject(0) { |s,e| e ? s+1 : s }
  end

  def match_at_least
    return @match_details[1] ? @match_details[1][1] : (@match_details[-2] ? @match_details[-2][1] : false)
  end

  def match_to_first
    return !!@match_details[-1] || !!@match_details[-2]
  end

  def match_from_first
    return !@match_details[-3]
  end

  def syllable_diagram_object_presence syllable_num
    return (@match_details[syllable_num]) ? "" : "no_syllable"
  end

  def syllable_diagram_object_colour syllable_num, chunk_num
    if @match_details[syllable_num]
      chunk = @match_details[syllable_num][chunk_num]
      if chunk[0]=="*"
        return "blue"
      elsif chunk[1]
        return "green"
      else
        return "red"
      end
    else
      return "blue"
    end
  end

  def syllable_diagram_object_phoneme syllable_num, chunk_num
    if @match_details[syllable_num]
      return @match_details[syllable_num][chunk_num][0]
    else
      return "*"
    end
  end

  def syllable_diagram_object_match syllable_num, chunk_num
    if @match_details[syllable_num]
      chunk = @match_details[syllable_num][chunk_num]
      if chunk[0]!="*" && chunk[1]
        return "checked=checked"
      end
    end
    return ""
  end

  def syllable_diagram_object_antimatch syllable_num, chunk_num
    if @match_details[syllable_num]
      chunk = @match_details[syllable_num][chunk_num]
      if chunk[0]!="*" && !chunk[1]
        return "checked=checked"
      end
    end
    return ""
  end

  def syllable_diagram_object_leading
    if @match_details[1]
      if @match_details[-2]
        # error
      end
      leading = @match_details[1]
    elsif @match_details[-2]
      leading = @match_details[-2]
    else
      return ""
    end
    if leading[1]
      return "#{leading[0]}+"
    else
      return "#{leading[0]}"
    end
  end

  def auto_complete number
    if @auto_complete == "words"
      auto_complete_words number
    elsif @auto_complete == "segments"
      auto_complete_segments number
    else
      []
    end
  end

  def auto_complete_words number
    return [] unless @term
    words = Spelling.where("label LIKE ?", "#{@term}%").limit(number).map { |sp| sp.words }.flatten
    words.map { |w| {
        :label => w.name, 
        :phonetic_label => w.pronunciation.label,
        :num_syllables => w.num_syllables,
        :id => w.id
      }
    }
  end

  # def auto_complete_segments number
  #   return [] unless @term
  #   if reversed_mode
  #     segments = Segment.select([:id,:label,:segment_type])
  #                    .where(["label LIKE ? AND segment_type > ?", "#{@term}%", 0])
  #                    .order(:label)
  #                    .limit(number)
  #     segments.map { |segment| {
  #         :label => segment.label, 
  #         :id => segment.id,
  #         :type => segment.segment_type
  #       }
  #     }
  #   else
  #     segments = Segment.select([:id,:label,:segment_type])
  #                       .where(["label LIKE ? AND segment_type < ?", "#{@term}%", 2])
  #                       .order(:label)
  #                       .limit(number)
  #     segments.map { |segment| {
  #         :label => segment.label, 
  #         :id => segment.id,
  #         :type => segment.segment_type
  #       }
  #     }
  #   end
  # end

  def dictionary_results text
    spelling = Spelling.where(label: text).first
    words = spelling.words
    linked_results = Word.select("words.id, lexemes.word_class, lexemes.gloss")
                         .where(:id => words.map(&:id))
                         .joins("LEFT JOIN word_lexemes ON word_lexemes.word_id = words.id
                                 LEFT JOIN lexemes ON lexemes.id = word_lexemes.lexeme_id")
                         .map(&:attributes)
                         .group_by { |r| r["id"] }
    word_id_to_syllables = Syllable.where(:pronunciation_id => words.map(&:pronunciation_id))
                                   .order("position ASC").group_by(&:pronunciation_id)
    words.each_with_index.map { |word,i| 
      syllables = word_id_to_syllables[word.pronunciation_id]
      lexemes = linked_results[word.id].each_with_index.map { |word_lexeme,j|
        if word_lexeme["word_class"] && word_lexeme["gloss"]
          "#{j+1}: (" + word_lexeme["word_class"] + ") " + word_lexeme["gloss"] + "."
        else 
          nil
        end
      }.compact
      word_hash = { name: spelling.label, num_syllables: syllables.length, 
                        lexemes: lexemes, word_id: word.id }
      { primary_word: word_hash, 
        other_words: [], 
        even_tag: (i%2==0) ? "even" : "odd",
        pronunciation_label: syllables.map(&:label).join("-"), 
        syllables: reversed_mode ? syllables : syllables.reverse }
    }
  end

  def params
    basic_params optional_params
  end

  def toggle_params
    basic_params({}, true)
  end

  def basic_params hash={}, toggle=false
    if (@dictionary == "1")
      hash[:text] = @text unless @text == ""
      hash[:dictionary] = "1" unless toggle
    elsif toggle
      hash[:text] = @text unless @text == ""
      hash[:dictionary] = "1"
    else
      hash[:text] = @text unless (@id || @text=="")
      hash[:id] = @id
    end
    hash
  end

  def optional_params hash={}
    if valid?
      hash[:word_type] = @word_type if @word_type.present?
      hash[:match_string] = @match_string if @match_string.present?
    end
    hash
  end

  def rhyming_link word_id
    # optional_params.merge({:id => word_id})
    {:id => word_id}
  end

  def words_to_show
    if @words_to_show_cached 
      # return that
    elsif !valid?
      @words_to_show_cached = []
    elsif dictionary_mode
      @words_to_show_cached = dictionary_results @word.name
    else
      @words_to_show_cached = run_query
    end
    @words_to_show_cached
  end

  def dictionary_mode
    @dictionary=="1"
  end

  def reversed_mode
    @reverse=="1"
  end

  def reversed_tag
    reversed_mode ? "reversed" : "normal_order"
  end

  def run_query

app/controllers/queries_controller.rb
class QueriesController < ApplicationController
  
  def create
  	@query = Query.new params[:query]
    respond_to do |format|
    	flash[:alert] = @query.errors.full_messages.to_sentence unless @query.valid?
    	format.html { redirect_to query_path(@query.params) }
    end
  end
  
  def show
  	@query = Query.new params
    @title_word = @query.text if @query.word
    respond_to do |format|
      if (params[:dictionary]!="1") && (!params.has_key?(:id)) && (@query.id)
        format.html { redirect_to query_path(@query.params) }
      else
        format.html # show.html.erb
      end
      format.json { render :json => @query.auto_complete(5).to_json }
    end
  end

end

app/helpers/queries_helper.rb
module QueriesHelper
end

app/views/queries/_search_bar.html.erb
<%= form_for @query, :url => query_path do |q| %>
  <div id="input_area">
    <div class="text_field">
      <% if @query.dictionary_mode %>
        <%= q.text_field :text, :value => "", :autocomplete => :off, :class => 'main-input' %>
      <% else %>
        <%= q.text_field :text, :value => "", :class => 'main-input' %>
      <% end %>
      <%= q.text_field :dictionary, :type => :hidden, :value => (@query.dictionary || "0") %>
    </div>
    <% if @query.dictionary == "0" %>
      <div class="rap_button_box">
        <%= q.submit "Rap", :class => 'rap_button' %>
      </div>
    <% else %> 
      <div class="rap_button_box">
        <%= q.submit "Search", :class => 'rap_button' %>
      </div>
    <% end %>
  </div>
<% end %>

<div id="wr_heading_row" class="word_table heading">
  <div class="word">
    <%= @query.text %>
  </div>
  <div class="controls">
    <!-- background -->
  </div>
  <div class="syllables"> <%= (@query.word.try(&:num_syllables) || "") unless (@query.dictionary=="1") %> </div>
  <div class="pronunciation <%= @query.reversed_tag %>">
    <% if @query.dictionary_mode %>
      <% syllables = [] %>
    <% else %>
      <% syllables = @query.word.try(&:syllables) || [] %>
    <% end %>
    <% if @query.reversed_mode %>
      <% syllables = syllables.reverse %>
    <% end %>
    <% syllables.each_with_index do |ph,j| %>
      <div class="spacer <%= @query.reversed_tag %>"><%= " . " unless j == 0 %></div>
      <div class="single_syllable <%= @query.reversed_tag %>"> <%= ph.label.gsub("-"," ") %> </div>
    <% end %>
  </div>
</div>

<script>
  $(document).ready(function() {
    var reset_hidden_fields = function() {
      $("#query_match_string").val("");
      $("#query_word_type").val("");
      $("#query_id").val("");
    };
    $("#query_text").change(function() {
      $("#wr_heading_row div.pronunciation").html("");
      $("#wr_heading_row div.syllables").html("");
      reset_hidden_fields();
    });
    $("#query_text").focus().val($("#query_text").val());
    if ($("#query_dictionary").val()!="1") {
      $(function() {
        $("#query_text").autocomplete({
          source: '<%= query_path(:json, {:autocomplete => "words"}) %>',
          select: function(event, ui) {
            $("#query_text").val(ui.item.label);
            $("#query_id").val(ui.item.id);
            if ($(".syllables").val()!="") {
              $("#wr_heading_row div.syllables").html(ui.item.num_syllables);
              if ($("#wr_heading_row div.pronunciation").hasClass("normal_order")) {
                $("#wr_heading_row div.pronunciation").html("<div class='single_syllable normal_order'>" + ui.item.reversed_phonemes.join("</div><div class='spacer normal_order'> - </div><div class='single_phoneme normal_order'>") + "</div>");
              } 
              else if ($("#wr_heading_row div.pronunciation").hasClass("reversed")) {
                $("#wr_heading_row div.pronunciation").html("<div class='single_syllable reversed'>" + ui.item.phonemes.join("</div><div class='spacer reversed'> - </div><div class='single_syllable reversed'>") + "</div>");
              }
            }
            $("#new_query").submit();
            return false;
          }
        }).data("uiAutocomplete")._renderItem = function(ul, item) {
          return $("<li></li>")
            .data("item.autocomplete", item)
            .append("<a><span class='autoleft'>" + item.label + " </span><span class='autoright'> " + item.phonetic_label + "</span></a>")
            .appendTo(ul);
          };
      });
    }
    $(function() {
      var available_segments;
      if ($(".first_segment_field span").html()=="Last segment:") {
        available_segments = "<%= query_path(:json, {autocomplete: 'segments', reverse: '1'}) %>"
      } else {
        available_segments = "<%= query_path(:json, {autocomplete: 'segments', reverse: '0'}) %>"
      }
      $("#query_first_segment_text").autocomplete({
        source: available_segments,
        select: function(event, ui) {
          $("#query_first_segment_text").val(ui.item.label);
          $("#query_first_segment").val(ui.item.id);
          return false;
        }
      }).data("uiAutocomplete")._renderItem = function(ul, item) {
        return $("<li></li>")
          .data("item.autocomplete", item)
          .append("<a><span>" + item.label + " </span></a>")
          .appendTo(ul);
        };
    });
  });
</script>

app/views/queries/_table.html.erb
<% @query.words_to_show.each_with_index do |result,i| %>
  <% word = result[:primary_word] %>
  <div id="wr_<%= i %>_" class="word_table word_row<%= (@query.word) ? " result_simple" : "" %>">
    <div class="word <%= result[:even_tag] %>"> 
      <!-- <%= word[:name] %>  -->
      <%= link_to word[:name], @query.rhyming_link(word[:word_id]) %>
      <%= "(+#{result[:other_words].length})" if result[:other_words].length > 0 %>
    </div>
    <div class="controls <%= result[:even_tag] %>">
      <!-- <b data-phonemes="<%= result[:pronunciation_label] %>" class="audio">P</b> -->
      <!-- <%= link_to "D", edit_word_path(word[:word_id]) %> -->
      <!-- <%= link_to "Rhyme", @query.rhyming_link(word[:word_id]) %> -->
      <% if word[:lexemes].length > 0 %>
        ↓
      <% elsif result[:other_words].length > 0 %>
        ↓
      <% end %>
    </div>
    <div class="syllables <%= result[:even_tag] %>"> 
      <%= word[:num_syllables] %> 
    </div>
    <div class="pronunciation <%= @query.reversed_tag %> <%= result[:even_tag] %>">
      <% matching = @query.dictionary=="0" %>
      <% result[:syllables].each_with_index do |syllable,j| %>
        <div class="spacer <%= @query.reversed_tag %> <%= "match" if matching %>"><%= " . " unless j == 0 %></div>
        <div class="single_syllable <%= @query.reversed_tag %> <%= "match" if matching %>"> <%= syllable.label.gsub("-"," ") %> </div>
      <% end %>
    </div>
  </div>
  <div id="wr_<%= i %>_extended" class="word_table result_extended">
    <% if word[:lexemes].length > 0 %>
      <div>
        <div class="lexeme_spacer <%= result[:even_tag] %>"> </div>
          <% word[:lexemes].each do |lexeme| %>
            <div class="lexemes <%= result[:even_tag] %>"><%= lexeme %></div>
          <% end%>
        <div class="lexeme_spacer <%= result[:even_tag] %>"> </div>
      </div>
    <% end %>
    <% result[:other_words].each do |other_word| %>
      <div class="word_row">
        <div class="word <%= result[:even_tag] %>"> 
          <!-- <%= other_word[:name] %>  -->
          <%= link_to other_word[:name], @query.rhyming_link(other_word[:word_id]) %>
        </div>
        <div class="buttons <%= result[:even_tag] %>"></div>
        <div class="controls <%= result[:even_tag] %>">
          <!-- <b data-phonemes="<%= result[:pronunciation_label] %>" class="audio">P</b> -->
          <!-- <%= link_to "D", edit_word_path(other_word[:word_id]) %> -->
          <!-- <%= link_to "Rhyme", @query.rhyming_link(other_word[:word_id]) %> -->
        </div>
        <div class="syllables <%= result[:even_tag] %>"> 
          <%= other_word[:num_syllables] %> 
        </div>
        <div class="pronunciation <%= @query.reversed_tag %> <%= result[:even_tag] %>">
          <% matching = @query.dictionary=="0" %>
          <% result[:syllables].each_with_index do |syllable,j| %>
            <div class="spacer <%= @query.reversed_tag %> <%= "match" if matching %>"><%= " . " unless j == 0 %></div>
            <div class="single_syllable <%= @query.reversed_tag %> <%= "match" if matching %>"> <%= syllable.label.gsub("-"," ") %> </div>
          <% end %>
        </div>
      </div>
      <div>
        <% if other_word[:lexemes].length > 0 %>
          <div class="lexeme_spacer <%= result[:even_tag] %>"> </div>
          <% other_word[:lexemes].each do |lexeme| %>
            <div class="lexemes <%= result[:even_tag] %>"><%= lexeme %></div>
          <% end%>
          <div class="lexeme_spacer <%= result[:even_tag] %>"> </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>
<% if (@query.dictionary=="1") && (@query.text != "") %>
  <div id="new_entry" class="word_table word_row<%= (@query.word) ? " result_simple" : "" %>">
    <div class="word <%= (@query.words_to_show.length%2==0) ? "even" : "odd" %>"> 
      <%= link_to "add new word...", new_word_path({:text => @query.text}), :class => "word_link" %> 
    </div>
    <div class="syllables <%= (@query.words_to_show.length%2==0) ? "even" : "odd" %>"> </div>
    <div class="phonemes <%= (@query.words_to_show.length%2==0) ? "even" : "odd" %>"> </div>
  </div>
<% end %>

<script type="text/javascript">
  $(".result_extended").each(function() {
    $(this).hide();
  });
  $(".result_simple").each(function() {
    $(this).hide();
  });
  // $("#wr_heading_row").hide();
  $(document).ready(function() {
    $(".result_simple").each(function() {
      $(this).slideDown(500);
    });
    // $("#wr_heading_row").show("slide", {direction: "down"}, 500);
    $(".result_simple").click(function() {
      if ($("#" + this.id + "extended").is(":visible")) {
        $(".result_extended").slideUp(500);
      } else {
        $(".result_extended").slideUp(500);
        $("#" + this.id + "extended").slideToggle(500);
      }
    });
    $("a").click(function(e) {
      e.stopPropagation();
      $(".result_extended").slideUp(500);
      $(".result_simple").slideUp(500);
      $(".diagram_box").slideUp(500);
      $("#wr_heading_row").hide("slide", {direction: "down"}, 500);
      $(".title_word").animate({"width": "toggle"}, 500);
      $(".title_word").hide("slide", {direction: "left"}, 500);

      // $(".title_word").toggleClass("visible");
    });
    $("#new_query").submit(function() {
      $(".result_extended").slideUp(500);
      $(".result_simple").slideUp(500);
      $(".diagram_box").slideUp(500);
      // $("#wr_heading_row").hide("slide", {direction: "down"}, 500);
      $(".title_word").animate({"width": "toggle"}, 500);
      $(".title_word").hide("slide", {direction: "left"}, 500);
      // $(".title_word").toggleClass("visible");
    });
  });
  $(".audio").click(function() {
    var audios = $.map($(this).data("phonemes").replace(/[0-9]*/g, "").split("-"), function(val,i) {
      sound = new Audio();
      if (sound.canPlayType('audio/mpeg')) {
        sound.src = "/audio/" + val + ".mp3";
        sound.accessKey = i;
      } else if (sound.canPlayType('audio/ogg')) {
        sound.src = "/audio/" + val + ".ogg";
        sound.accessKey = i;
      } else {
        sound.src = null;
        sound.accessKey = i;
      }
      return sound;
    });
    for (var i = 0; i < (audios.length-1); i++) {
      audios[i].addEventListener("ended", function() { 
        audios[parseInt($(this)[0].accessKey)+1].play();
      }, true);
    }
    audios[0].play();
  });
</script>

app/views/queries/show.html.erb
<%= render "layouts/title" %>
<%= render "search_bar" %>
<div class="diagram_box">
<% if @query.word && !@query.dictionary_mode %>
	<%= render "diagram" %>
<% end %>
</div>
<div id="results_table">
  <%= render "table" %> 
</div>

<script type="text/javascript">
  if ($("#query_dictionary").val()=="1") {
    $("a.word_link").css("color", "rgba(200, 0, 40, 1)");
    $("div.title_word").css("color", "rgba(200, 0, 40, 1)");
    $("#query_text").css("color", "rgba(200, 0, 40, 1)");
    $("div.heading").css("color", "rgba(200, 0, 40, 1)");
  }
</script>